[build]
  # This command starts your server, make sure it's correct for your setup.
  command = "npm run dev"
  
  # This is where Netlify will look for serverless functions.
  functions = "netlify/functions"
  
  # Since you're serving dynamic content, you may not need to specify a `publish` directory.
  publish = ""

  ## Optional: Redirects configuration if needed
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## Optional: Configuration for Netlify Dev
  #[dev]
  #  command = "npm start" # or "yarn start" if using Yarn
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file
